services:
  olivos:
    image: ghcr.io/cary17/olivos:latest  # 生产版（含OPK插件）
    # image: ghcr.io/cary17/olivos:latest-core # 核心版（核心 + 插件生态，无 OPK 插件）
    # image: ghcr.io/cary17/olivos:latest-dev  # 开发版（无OPK插件，含开发工具）
    container_name: olivos
    restart: always
    volumes:
      - /opt/olivos/conf:/app/OlivOS/conf
      - /opt/olivos/plugin:/app/OlivOS/plugin
    environment:
      TZ: Asia/Shanghai
      # 添加额外 pip 依赖，多个用空格分隔
      #EXTRA_PACKAGES: "psutil==5.9.0 lxml>=4.9"
