services:
  olivos:
    image: ghcr.io/cary17/olivos:latest  # 正式版（含 OPK 插件）
    # image: ghcr.io/cary17/olivos:latest-core   # 正式核心版
    # image: ghcr.io/cary17/olivos:latest-dev    # 正式开发版
    # image: ghcr.io/cary17/olivos:testing       # 测试版（Pre-release）
    # image: ghcr.io/cary17/olivos:testing-core  # 测试核心版
    # image: ghcr.io/cary17/olivos:testing-dev   # 测试开发版
    container_name: olivos
    restart: always
    volumes:
      - /opt/olivos/conf:/app/OlivOS/conf
      - /opt/olivos/plugin:/app/OlivOS/plugin
    environment:
      TZ: Asia/Shanghai
